a = input('Digite algo: ')
print('Qual o tipo primivito: ', type(a))
print('É um valor numérico? ', a.isnumeric())
print('É um constituido somente de espaço? ', a.isspace())
print('É alfabético? ', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Está em maiusculo? ', a.isupper())
print('Está em minusculo? ', a.islower())
print('Está capitalizado? ', a.istitle())